# Generated by Django 4.1.5 on 2023-03-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='name',
            new_name='namee',
        ),
    ]
