# Generated by Django 4.1.5 on 2023-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_desc_picture_descr_rename_img_picture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pt'),
        ),
    ]
