# Generated by Django 4.1.5 on 2023-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_alter_picture_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='place',
            name='descr',
            field=models.TextField(default='e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='e', upload_to='pt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='namee',
            field=models.CharField(default='r', max_length=150),
            preserve_default=False,
        ),
    ]
