# Generated by Django 4.1.5 on 2023-03-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_alter_place_descr_alter_place_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='namee',
        ),
    ]
